# Generated by Django 5.2.17 on 2026-09-30 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('achieved_on', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('issuer', models.CharField(max_length=140)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=180)),
                ('degree', models.CharField(max_length=160)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gpa', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=180)),
                ('role', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('achievements', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('biography', models.TextField()),
                ('career_objective', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('photo_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('available_for_work', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=280)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('web', 'Web'), ('ai', 'AI'), ('other', 'Other')], default='web', max_length=20)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools')], max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=140)),
                ('organization', models.CharField(blank=True, max_length=140)),
                ('quote', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('sort_order', '-created_at'),
                'abstract': False,
            },
        ),
    ]
