# Generated by Django 5.2.17 on 2026-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprofile',
            name='linkedin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
    ]
